name: need_food
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.32.0
  firebase_auth: ^4.4.0
  firebase_database: ^10.0.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.7.7
  image_picker: ^1.1.2
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/logo.png
